trigger:
- main  # Define the branch to trigger the pipeline on

pool:
  name: 'my-computer'  # Use the self-hosted agent pool

variables:
  buildConfiguration: 'production'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'  # Specify the version of Node.js to use
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build-prod
  displayName: 'Build Angular App'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)/dist'
    artifactName: 'angular-app'
  displayName: 'Publish Build Artifacts'
